title: Work Term Report
description: Work Term Report Website for COOP
#logo: assets/img/headshot.png
# description: Computer Science Student
# show_downloads: true
#google_analytics: G-ZD7T1JJXB5
#theme: jekyll-theme-minimal
theme: jekyll-theme-leap-day